// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkTDZH4yjMghsyOMDN5WYemQA3cTy3l0',
    appId: '1:1067677162128:web:9559c6d76bff82a7b39615',
    messagingSenderId: '1067677162128',
    projectId: 'project-7132f',
    authDomain: 'project-7132f.firebaseapp.com',
    storageBucket: 'project-7132f.firebasestorage.app',
    measurementId: 'G-KBCG99KK9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1BAAja4ANa4eTJwty4muwRzfOWBBvYM',
    appId: '1:1067677162128:android:b85e51bb980ff07eb39615',
    messagingSenderId: '1067677162128',
    projectId: 'project-7132f',
    storageBucket: 'project-7132f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALHa4tUB8d6-OSzEe7KIjXAL_l2yU2aRM',
    appId: '1:1067677162128:ios:0b54e72d8f118375b39615',
    messagingSenderId: '1067677162128',
    projectId: 'project-7132f',
    storageBucket: 'project-7132f.firebasestorage.app',
    iosBundleId: 'com.example.farmerRetailerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALHa4tUB8d6-OSzEe7KIjXAL_l2yU2aRM',
    appId: '1:1067677162128:ios:0b54e72d8f118375b39615',
    messagingSenderId: '1067677162128',
    projectId: 'project-7132f',
    storageBucket: 'project-7132f.firebasestorage.app',
    iosBundleId: 'com.example.farmerRetailerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMkTDZH4yjMghsyOMDN5WYemQA3cTy3l0',
    appId: '1:1067677162128:web:e980e8a748cd8c58b39615',
    messagingSenderId: '1067677162128',
    projectId: 'project-7132f',
    authDomain: 'project-7132f.firebaseapp.com',
    storageBucket: 'project-7132f.firebasestorage.app',
    measurementId: 'G-FQGQQ0Y5XH',
  );

}